-- CreateTable
CREATE TABLE "pharmacy_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "pharmacyName" TEXT NOT NULL DEFAULT 'Pharmablaze Pharmacy',
    "phone" TEXT NOT NULL DEFAULT '0912 828 6533',
    "email" TEXT,
    "address" TEXT NOT NULL DEFAULT '2V56+V39, 235 Abak Rd, Uyo 520104, Akwa Ibom',
    "website" TEXT,
    "facebook" TEXT,
    "instagram" TEXT,
    "monday" TEXT NOT NULL DEFAULT '8:00 AM - 8:00 PM',
    "tuesday" TEXT NOT NULL DEFAULT '8:00 AM - 8:00 PM',
    "wednesday" TEXT NOT NULL DEFAULT '8:00 AM - 8:00 PM',
    "thursday" TEXT NOT NULL DEFAULT '8:00 AM - 8:00 PM',
    "friday" TEXT NOT NULL DEFAULT '8:00 AM - 8:00 PM',
    "saturday" TEXT NOT NULL DEFAULT '9:00 AM - 6:00 PM',
    "sunday" TEXT NOT NULL DEFAULT 'Closed',
    "storeEnabled" BOOLEAN NOT NULL DEFAULT true,
    "allowOrders" BOOLEAN NOT NULL DEFAULT true,
    "requireConfirmation" BOOLEAN NOT NULL DEFAULT true,
    "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
    "deliveryFee" DECIMAL(12,2) NOT NULL DEFAULT 1500,
    "freeDeliveryMinimum" DECIMAL(12,2) NOT NULL DEFAULT 50000,
    "paymentOnConfirmation" BOOLEAN NOT NULL DEFAULT true,
    "onlinePayment" BOOLEAN NOT NULL DEFAULT false,
    "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "orderNotifications" BOOLEAN NOT NULL DEFAULT true,
    "reviewNotifications" BOOLEAN NOT NULL DEFAULT true,
    "messageNotifications" BOOLEAN NOT NULL DEFAULT true,
    "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
    "sessionTimeout" INTEGER NOT NULL DEFAULT 60,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "pharmacy_settings_pkey" PRIMARY KEY ("id")
);
